flowchart LR
    classDef actor fill:#fef3c7,color:#78350f,stroke:#b45309,stroke-width:2px
    classDef uc fill:#dbeafe,color:#1e3a8a,stroke:#1e3a8a,rx:30,ry:30,stroke-width:1px

    A0[👤 محلل البيانات]:::actor
    A1[👤 المدير]:::actor
    A2[👤 مكتب التربية]:::actor
    A3[👤 الوزارة]:::actor

    U0((إعداد مسودة إحصائية)):::uc
    U1((مراجعة الإحصائية)):::uc
    U2((رفع الإحصائية)):::uc
    U3((اعتماد الإحصائية)):::uc
    U4((أرشفة الإحصائيات)):::uc
    U5((سجل التحديثات)):::uc
    U6((توليد تقرير دوري)):::uc
    U7((اعتماد التقارير)):::uc
    U8((تقارير مقارنة)):::uc
    U9((تحليل الفجوة)):::uc
    U10((تقارير امتثال)):::uc
    U11((تقارير مالية مجمعة)):::uc
    U12((أرشفة التقارير)):::uc
    U13((لوحة مؤشرات الأداء)):::uc
    U14((استخراج إحصائيات استثنائية)):::uc

    A0 --> U0
    A1 -.-> U0
    A1 --> U1
    A2 --> U2
    A3 --> U3
    A0 -.-> U3
    A0 --> U4
    A1 --> U5
    A2 --> U6
    A3 -.-> U6
    A3 --> U7
    A0 --> U8
    A1 --> U9
    A2 -.-> U9
    A2 --> U10
    A3 --> U11
    A0 --> U12
    A1 -.-> U12
    A1 --> U13
    A2 --> U14
