flowchart LR
    classDef actor fill:#fef3c7,color:#78350f,stroke:#b45309,stroke-width:2px
    classDef uc fill:#dbeafe,color:#1e3a8a,stroke:#1e3a8a,rx:30,ry:30,stroke-width:1px

    A0[👤 مدير النظام]:::actor
    A1[👤 مسؤول الأمن]:::actor
    A2[👤 المستخدم]:::actor
    A3[👤 المدقق]:::actor

    U0((إنشاء حساب مستخدم)):::uc
    U1((تفعيل/تعطيل الحساب)):::uc
    U2((إعادة تعيين كلمة المرور)):::uc
    U3((تسجيل الدخول)):::uc
    U4((تسجيل الخروج)):::uc
    U5((إنشاء دور)):::uc
    U6((تعديل الدور)):::uc
    U7((ربط مستخدم بدور)):::uc
    U8((إنشاء صلاحية)):::uc
    U9((ربط صلاحية بدور)):::uc
    U10((صلاحية مباشرة لمستخدم)):::uc
    U11((سياسات الوصول)):::uc
    U12((حوكمة الأدوار)):::uc
    U13((تتبع نشاط المستخدم)):::uc
    U14((سجل التدقيق)):::uc
    U15((تقرير محاولات الاختراق)):::uc
    U16((إدارة الجلسات)):::uc
    U17((قواعد الامتيازات)):::uc
    U18((مصفوفة الأدوار)):::uc
    U19((صلاحيات الطالب)):::uc
    U20((صلاحيات السلوك)):::uc
    U21((صلاحيات المالية للطالب)):::uc

    A0 --> U0
    A1 -.-> U0
    A1 --> U1
    A2 --> U2
    A3 --> U3
    A0 -.-> U3
    A0 --> U4
    A1 --> U5
    A2 --> U6
    A3 -.-> U6
    A3 --> U7
    A0 --> U8
    A1 --> U9
    A2 -.-> U9
    A2 --> U10
    A3 --> U11
    A0 --> U12
    A1 -.-> U12
    A1 --> U13
    A2 --> U14
    A3 --> U15
    A0 -.-> U15
    A0 --> U16
    A1 --> U17
    A2 --> U18
    A3 -.-> U18
    A3 --> U19
    A0 --> U20
    A1 --> U21
    A2 -.-> U21
